[data] stringify cutscenes.s
pret/pmd-red pull request #159
Opened 2023-09-24 03:41 UTC by rpadaki

For this PR, I added a bunch of heuristics to the script I used for #157. This lets me find most of the strings in this file, though it's very possible that I'm missing some.
- If I see an unknown byte, I log it and assume the whole block is not a string
- If a block is less than 5 bytes, I assume it's not a string (or small enough that we can do those by hand when they come up)
- If a block ends with 5 or more null bytes, I assume it's not a string (Something something alignment? This is totally a heuristic)

The more complete `charmap.txt` is, the more strings I can find. The script is a little too finicky to be shared rn but I'll clean it up when I have time.

2023-09-24 03:47 UTC, AnonymousRandomPerson approved these changes
Will let https://github.com/pret/pmd-red/pull/158 merge before this, per Discord convo.

2023-09-24 17:06 UTC, SethBarberee approved these changes

2023-09-25 15:46 UTC, SethBarberee commented
Needs rebase

2023-09-25 19:58 UTC, SethBarberee requested changes

2023-09-25 19:58 UTC, SethBarberee commented on charmap.txt
> +ARG_MOVE_ITEM_0 = 24 69 30 @ $i0
Already defined so CI is erroring out
```suggestion
```

2023-09-25 19:58 UTC, SethBarberee commented on charmap.txt
> +ARG_MOVE_ITEM_1 = 24 69 31 @ $i1
Need to remove since already defined
```suggestion
```

2023-09-26 00:03 UTC, SethBarberee approved these changes

2023-09-26 00:08 UTC, merged