Ground scripts
pret/pmd-red pull request #230
Opened 2024-10-14 21:59 UTC by mateon1

2024-10-14 22:09 UTC, SethBarberee requested changes

2024-10-14 22:09 UTC, SethBarberee commented on scripts/__pycache__/scripts.pypy310.pyc
Accidentally included?

2024-10-14 22:09 UTC, SethBarberee commented on scripts/__pycache__/scriptvars.pypy310.pyc
Ditto on all pycache ones

2024-10-14 22:09 UTC, SethBarberee commented on include/personality_test1.h
> +    /* 0x8 */ const u8 (*effects)[16];
Maybe a good idea to bind this to `NUM_PERSONALITIES + 3` or modify the enum of personalities so we can bound this with a constant and allow hackers to increase/decrease these later.

2024-10-14 22:09 UTC, SethBarberee commented on src/personality_test1.c
> +    const u8 (*pointArray)[16];
Same comment as the include file with bounding this with an enum value.

2024-10-14 22:53 UTC, SethBarberee approved these changes

2024-10-15 02:41 UTC, AnonymousRandomPerson commented on src/data/ground/ground_data_a01p01_station.h
> +    { 0x33, 0x00,  0x0000,  0x00000000,  0x00000000, _("Maybe...#W Is this a dream...?") },
`#W` is mapped to the macro `WAIT_PRESS`. Can we use this macro in all these strings?

2024-10-15 02:41 UTC, AnonymousRandomPerson commented on src/data/ground/ground_data_a01p01_station.h
> +    { 0x33, 0x00,  0x0000,  0x00000000,  0x00000000, _("Ga...#W$n2!") },
`$n2` is a placeholder for a nickname, which is represented by the macro `ARG_NICKNAME_2`. Is it possible to use these argument macros throughout the scripts?

2024-10-15 08:56 UTC, mateon1 commented
Honestly, those charmap macros read worse to me than the format codes (with exception of color). But yeah, I can do that. Will have to wait until friday/saturday since I will be away from any decent computers for a while.

2024-10-15 15:16 UTC, mateon1 commented
Managed to do it before I had to go out, everything should be addressed

2024-10-15 15:29 UTC, AnonymousRandomPerson approved these changes

2024-10-15 15:30 UTC, merged