Oct 2024
pret/pmd-red pull request #234
Opened 2024-10-18 15:10 UTC by SethBarberee

2024-10-18 15:21 UTC, DizzyEggg commented on src/code_8057824_1.c
> +  Entity *LeaderEntity;
Nitpick, but I'm used to variables using camelCase, so `LeaderEntity` becomes `leaderEntity`. 👀

2024-10-27 04:12 UTC, SethBarberee commented
Ready for review

2024-10-27 15:34 UTC, DizzyEggg requested changes

2024-10-27 15:34 UTC, DizzyEggg commented on src/code_8069E0C.c
> +// https://decomp.me/scratch/tBuxP (90.38% matching - Seth)
I was able to fakematch it, here https://decomp.me/scratch/qLr3r

2024-10-27 16:53 UTC, AnonymousRandomPerson approved these changes

2024-10-27 16:53 UTC, merged